### PR TITLE
CP-1122 Bash completions

### PR DESCRIPTION
**Pull request by georgelesica-wf**
## Problem

People don't like typing, and dart_dev makes people type commands.

## Solution

Add some Bash completions to dart_dev. I did these for myself and I thought maybe other people would want to use them as well.

They operate on the expectation that the `ddev` alias exists.

## FYI

@evanweible-wf

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
Cool! Any idea if this would work with zsh as well?

**Comment by georgelesica-wf** [comment]
I spent a few minutes looking at the zsh completion documentation. It is pretty dense. I'm sure it could be done easily by someone with the requisite knowledge, however.

**Comment by georgelesica-wf** [comment]
I'm going to add completions for subcommands as well. So please don't merge this yet. I should have mentioned that in the description. I just wanted to get it up here to get some feedback. If people are interested in zsh, I can definitely look into it. @bencampbell-wf is kind of a zsh wizard, so maybe he would be willing to put a few minutes into it as well.

**Comment by evanweible-wf** [comment]
This is awesome! I would also be interested in zsh completions :smiley:

**Comment by bencampbell-wf** [comment]
It looks like the completion definitions for zsh are a cinch. The trick is installing them. While bash has a defacto user directory you can symlink your completion scripts into, zsh requires and update to `$fpath` before `compinit` runs.

I can take a crack at it if it's wanted.

**Comment by georgelesica-wf** [comment]
OK, I'm pretty happy with the Bash completions at this point. @bencampbell-wf if you want to you can add zsh completions to this PR so we get them in all at once. Or we can do them separately.

**Comment by georgelesica-wf** [comment]
@evanweible-wf oh there wouldn't be a problem if it doesn't exist, it just only does completion if you use `ddev` as the command.

**Comment by trentgrover-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
Oh, duh :smile:

+1

**Comment by trentgrover-wf** [comment]
@jayudey-wf ready for merge

@bencampbell-wf if you get zsh magic together, please submit as a separate PR (I know I'd use it...)

**Comment by georgelesica-wf** [comment]
I realized I was making some assumptions about the environment people will have, so I added a bit more explanation to the README.

**Comment by georgelesica-wf** [comment]
I'm not sure why the build is failing, I didn't change any code...

**Comment by evanweible-wf** [comment]
It's an issue with Dart 1.13, I'm looking into it

**Comment by evanweible-wf** [comment]
Also +1 to the readme updates.

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - verified that completion works as expected on `ddev` tasks
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Pull request merged**
