### PR TITLE
CP-1400 Release dart_dev 1.1.2

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-1400

Releases that need to go out at the same time (if any): 

JIRA and PR's included in this release: 

 CP-1453  - Upgrade to coverage 0.7.3 to fix coverage issues  - https://github.com/Workiva/dart_dev/pull/140

 CP-1480  - Test Task correctly build the set of tests to run and respect the nocolor flag  - https://github.com/Workiva/dart_dev/pull/141

 CP-1524  - Coverage tests were routinely timing out on travis.ci  - https://github.com/Workiva/dart_dev/pull/143

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.1.1...CP-1400_release_1.1.2

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
