### PR TITLE
CP-2383 Release dart_dev 1.4.2

### PR DESCRIPTION
**Pull request by rmconsole3-wf**
Pulls Included in Release:
* [CP-2388 Fix slash bug](https://github.com/Workiva/dart_dev/pull/168)
* [CP-2404 Fix bug when gen-test-runner --check runs on Smithy](https://github.com/Workiva/dart_dev/pull/169)

Requested by: charliekump-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.4.1...version-bump-dart_dev-1-4-2
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.4.1...1.4.2

### CODE REVIEW

**Comment by rmconsole-wf** [comment]
@rmconsole3-wf, @edjackson+rmconsole-wf
* It looks like you have not included any tickets in the title of this PR, but this repo requires tickets for all pull requests. Please create a ticket for this change, or click <a href='https://w-rmconsole.appspot.com/api/v1/pulls/86011645/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
