### PR TITLE
CP-2767 Release dart_dev 1.5.1

### PR DESCRIPTION
**Pull request by rmconsole2-wf**
Pulls Included in Release:
* [CP-2824 Fixes for compatibility with Dart 1.20.x](https://github.com/Workiva/dart_dev/pull/183)
* [CP-2858 Update gen-test-runner task based on feedback](https://github.com/Workiva/dart_dev/pull/184)

Requested by: @charliekump-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.5.0...version-bump-dart_dev-1-5-1
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.5.0...1.5.1

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
@jayudey-wf ready for you

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
