### PR TITLE
CP-1167 Dart formatter updates for dart_dev, dart_style 0.2.1.

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
- `dart_style` 0.2.1 is out with improved formatting

## Changes
- Apply newest formatting
- Bump `dart_style` minimum version to 0.2.1

## Areas of Regression
- n/a

## Testing
- n/a

## Code Review
@trentgrover-wf
@maxwellpeterson-wf 
@dustinlessard-wf
@jayudey-wf

### CODE REVIEW

**Comment by dustinlessard-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - passing CI
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Pull request merged**
