### PR TITLE
WP-4404 Loosen dartdoc range

### PR DESCRIPTION
**Pull request by travissanderson-wf**
Loosen dartdoc range

### CODE REVIEW

**Comment by travissanderson-wf** [comment]
@maxwellpeterson-wf can you re-review? I forgot how to pubspec :)

**Comment by travissanderson-wf** [comment]
@jayudey-wf any idea what is up with that test? it passes locally and in Smithy, maybe travis-ci is on an old Dart SDK?

**Comment by travissanderson-wf** [comment]
oh yeah it is on 1.19.1! https://github.com/Workiva/dart_dev/blob/master/.travis.yml#L3

**Comment by travissanderson-wf** [comment]
hmm allegedly that is the same as Smithy though.. I bumped it up to 1.23.0, I guess we shall see..

**Comment by travissanderson-wf** [comment]
maybe an intermittent timeout? it passed this time

**Comment by rmconsole2-wf** [comment]
Sorry, I could not create a JIRA ticket for this pull.

I sent the following data to JIRA:
`{'issuetype': {'name': u'Task'}, 'project': {'key': u'WP'}, 'description': '', 'components': [{'name': u'dart_dev'}], 'summary': 'Loosen dartdoc range'}`

I received the following data from JIRA:
`Hidden on Open Source Repos`

If this is an issue that you cannot resolve, please reach out to RM in the Release Management chat room.

**Comment by maxwellpeterson-wf** [comment]
+10
- CI passed

**Comment by maxwellpeterson-wf** [comment]
QA +1
- [x] Minimum dependency bump only
- [x] Dev +1's
- [x] CI passes
- [x] Dependency scan clean

@Workiva/release-management-pp

**Comment by rmconsole-wf** [comment]
+1 from RM

**Pull request merged**
