### PR TITLE
CP-1334 copy-license: catch FSE when reading non-utf8 file

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
- The copy-license task iterates over all files in the specified directories, reading their contents to determine if a license needs to be applied. If any of these files are not UTF8-decodable, an exception will be thrown (`.DS_Store` for example).

## Changes
**Source:**
- Catch `FileSystemException`s when reading the file contents and throw a `NonUtf8EncodedFileException`.
- Catch `NonUtf8EncodedFileException` and ignore to allow the task to complete.

**Tests:**
- Added a non-UTF8 file to the test fixture that should be ignored.

## Areas of Regression
- copy-license task

## Testing
- CI passes.

## Code Review
@trentgrover-wf
@maxwellpeterson-wf 
@dustinlessard-wf
@jayudey-wf

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
code lgtm, but CI has test failures

**Comment by evanweible-wf** [comment]
fyi, CI failure is due to coverage being broken (see https://github.com/dart-lang/coverage/issues/104)

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - verified that copy-license task was appropriately ignoring non-utf8 encoded files
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Pull request merged**
