### PR TITLE
CP-1524 Coverage tests were routinely timing out on travis.ci

### PR DESCRIPTION
**Pull request by jayudey-wf**
## Issue
- Tests were intermittently timing out during a part of the CI

## Changes
**Source:**
- Extended timeout

**Tests:**
- n/a

## Areas of Regression
- n/a

## Testing
- Passing CI

## Code Review
@trentgrover-wf
@maxwellpeterson-wf
@evanweible-wf
@dustinlessard-wf

### CODE REVIEW

**Comment by evanweible-wf** [comment]
+1

**Comment by johnbland-wf** [comment]
Is this going to free us up for a new tag?

**Comment by trentgrover-wf** [comment]
QA +10
- test only change (to timeout values)
- test pass smithy CI
@jayudey-wf merge when ready

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - performed and documented by Trent
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Pull request merged**
