### PR TITLE
CP-3445 Release dart_dev 1.7.2

### PR DESCRIPTION
**Pull request by rmconsole-wf**
Pulls Included in Release:
* [CP-3485 Pub serve single instance for coverage](https://github.com/Workiva/dart_dev/pull/212)
* [RAP-1618 Skip files in .pub directories when formatting](https://github.com/Workiva/dart_dev/pull/213)

Requested by: @jayudey-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.7.1...version-bump-dart_dev-1-7-2
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.7.1...1.7.2

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for you

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
