### PR TITLE
Add docstrings to coverage config

### PR DESCRIPTION
**Pull request by travissanderson-wf**
I didn't add any for after/before functional tests yet because those aren't in the README either.

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
<details>
<summary>Number of Findings: 0</summary>

</details>

**Comment by patkujawa-wf** [comment]
+1 CR

**Comment by jayudey-wf** [comment]
@travissanderson-wf could you format the branch :(

**Comment by patkujawa-wf** [comment]
Bender can!

**Comment by travissanderson-wf** [comment]
there's nothing Bender can't do!

**Comment by jayudey-wf** [comment]
QA +1 doc change only

Merging into master

**Comment by jayudey-wf** [comment]
@Workiva/release-management-pp

**Pull request merged**
