### PR TITLE
Update gen-test-runner task based on feedback

### PR DESCRIPTION
**Pull request by jayudey-wf**
## Issue
- There was no way of knowing what command was used generated the 'generated file.'
- When running the gen-test-runner task with the `check` flag the html was being overwritten

## Changes
**Source:**
- Added line to document the command used to generate the test runner
- Don't create html file on check task

**Tests:**
- modified current tests

## Areas of Regression
- failing tests

## Testing
- passing CI (current failures should be addressed by https://github.com/Workiva/dart_dev/pull/183)

## Code Review
@trentgrover-wf
@maxwellpeterson-wf
@evanweible-wf
@dustinlessard-wf

## FYI
@dustyholmes-wf 
@spencerbradley-wf

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
QA +1
- [x] Testing instruction
- [x] Dev +1's
- [x] Dev/QA +10 with detail of what was tested
- [x] Unit tests created/updated 
- [x] All unit tests pass
  - manual CI

Merging into master.

**Pull request merged**
