### PR TITLE
CP-859 Codecov.io, dart_dev

### PR DESCRIPTION
**Pull request by evanweible-wf**
_Dependent on #39._

## Issue
#30 Setup codecov.io reporting.

## Changes
- Add bash reporter step to travis CI build.
- Add codecov.io badge to readme

## Areas of Regression
- n/a

## Testing
- CI build runs and passes and the codecov bash reporter successfully found the `coverage.lcov` file and uploaded it to codecov.io (build logs should indicate this).
- Codecov report should show up here: https://codecov.io/github/Workiva/dart_dev

## Code Review
@trentgrover-wf
@maxwellpeterson-wf 
@dustinlessard-wf
@jayudey-wf

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1
assuming that the CI ever finishes...
(from reviewing https://github.com/Workiva/dart_dev/compare/travis...codecov)

**Comment by evanweible-wf** [comment]
@trentgrover-wf @maxwellpeterson-wf @dustinlessard-wf rebased on latest master, and it is now correctly reporting only one coverage.lcov file.

**Comment by trentgrover-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - coverage is accurately reported to coverage.io
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Pull request merged**
