### PR TITLE
CP-1072 Release dart_dev 1.0.2

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-1072

JIRA and PR's included in this release: 

 CP-1070  - Format: allow exclusions  - https://github.com/Workiva/dart_dev/pull/81
 CP-1063  - Running coverage on non_test dart files  - https://github.com/Workiva/dart_dev/pull/78
 CP-1069  - Copy License: trim leading/trailing empty lines  - https://github.com/Workiva/dart_dev/pull/80
 CP-1071  - Update CHANGELOG.md 1.0.2  - https://github.com/Workiva/dart_dev/pull/82

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.0.1...CP-1072_release_1.0.2

### CODE REVIEW

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf ready to go

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
