### PR TITLE
CP-2946 Adding smithy.yaml

### PR DESCRIPTION
**Pull request by jayudey-wf**
## Issue
- We needed to add a smithy.yaml for release management to more easily track dependencies.

## Changes
**Source:**
- Included smithy.yaml

**Tests:**
- n/a

## Areas of Regression
- passing CI's

## Testing
- passing CI

## Code Review
@maxwellpeterson-wf
@evanweible-wf
@dustinlessard-wf
@sebastianmalysa-wf

### CODE REVIEW

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for you

**Comment by charliekump-wf** [comment]
+10 CI Passes

**Comment by charliekump-wf** [comment]
Quality Review Approval: +1

- [x] Testing instruction
- [x] Dev +1's
- [x] Dev/QA +10 with detail of what was tested
- [ ] Unit test created/updated -N/A
- [x] All unit tests pass 

Merging into master.

**Comment by colefeisthamel-wf** [comment]
RM +1 
updated Rosie functions

**Pull request merged**
