### PR TITLE
CP-961 Fix formatting of README, update CHANGELOG

### LINKED ISSUE #48: Fix readme formatting on pub
https://pub.dartlang.org/packages/dart_dev

## Issues
- GitHub tables are not standard markdown - use HTML tables instead
- Blockquotes end to early..
  - at the beginning rationale
  - under "CLI Usage"
  - under "Programmatic Usage"
- Headers under "Getting Started" are too small
- "Project Configuration" code block is missing most of the code?

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
- The readme has several formatting errors when rendered on pub.dartlang.org (#48)
- The changelog is missing the updates that have been merged since 1.0.0

## Changes
- Updated README for better rendering on pub.dartlang.org (resolves #48)
- Added missing info to CHANGELOG

> Displaying the "rich diff" for these files will be helpful since I changed the line length throughout the README and I switched to HTML tables from GitHub's simpler table syntax.

## Areas of Regression
n/a

## Testing
n/a - we can't really determine how this will look on pub.dartlang.org until it's published there.

## Code Review
@trentgrover-wf
@maxwellpeterson-wf 
@dustinlessard-wf
@jayudey-wf

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
### TODO
- [ ] Update changelog once https://github.com/Workiva/dart_dev/pull/69 is merged (doing it here to avoid merge conflict)

**Comment by evanweible-wf** [comment]
@trentgrover-wf @maxwellpeterson-wf @dustinlessard-wf rebased on latest master, added the change from #69 to the changelog.

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf docs only change

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA +1 doc change only

Merging into master

**Pull request merged**
