### PR TITLE
CP-1071 Update CHANGELOG.md 1.0.2

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Changes
Update `CHANGELOG.md` for 1.0.2 release.

## Areas of Regression
n/a

## Testing
n/a

## Code Review
@trentgrover-wf
@maxwellpeterson-wf 
@dustinlessard-wf
@jayudey-wf

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA +1, doc change only

Merging into master

**Comment by jayudey-wf** [comment]
@rosie run_merge_script

**Comment by jayudey-wf** [comment]
@rosie run_merge_script

**Pull request merged**
