### PR TITLE
Add additional configuration options to functional coverage / test task

### PR DESCRIPTION
**Pull request by jayudey-wf**
## Issue
- There were issues trying to set up the before and after commands needed for the functional tasks that wouldn't negatively impact other tasks.

## Changes
**Source:**
- Added the ability to specify tasks to be run exclusively before functional tasks.

**Tests:**
- updated

## Areas of Regression
- functional coverage / testing
- before and after commands for other tasks

## Testing
- CI
- install into a project and ensure that newly added (and historical) functionality is working as expected

## Code Review
@Workiva/web-platform-pp 
@joewaters-wf

### CODE REVIEW

**Comment by evanweible-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by joewaters-wf** [comment]
+10. Tested through https://github.com/joewaters-wf/w_context_menu/pull/1 WIP branch consuming these changes.

**Comment by evanweible-wf** [comment]
QA +1
- [X] Testing instruction
- [X] Dev +1's
- [X] Dev/QA +10 with detail of what was tested
- [X] Unit tests created/updated 
- [X] All unit tests pass

Merging into master.

**Pull request merged**
