### PR TITLE
Update to latest image of github ci verifier

### PR DESCRIPTION
**Pull request by sourcegraph-wk**
This updates to the latest image of the github ci verifier and changes on on-pull-request to true

[_Created by Sourcegraph batch change `wesleybalvanz-wf/image-update`._](https://sourcegraph.plat.workiva.net/users/wesleybalvanz-wf/batch-changes/image-update)

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by sourcegraph-wk** [comment]
This image of the github ci verifier uses an etag on repeat requests so if there is on change it doesn't count towards the rate limit which allows us to run these on PR's as well as releases.

**Review by evanweible-wf — APPROVED** [review]

**Comment by autobot-wf** [comment]
Skynet test results failed initially for this build but were approved by evan.weible
https://wf-skynet-hrd.appspot.com/apps/test/smithy/3732598/1
Approval message: Known failure on dev channel of Dart SDK, will be fixed by upgrading dependencies.

**Comment by evanweible-wf** [comment]
QA +1 CI passes
@Workiva/release-management-p

**Pull request merged**
