### PR TITLE
CP-1225 add docs badge, dart_dev

### PR DESCRIPTION
**Pull request by trentgrover-wf**
## Issue
- add docs badge

## Changes
**Source:**
- none

**Tests:**
- none

## Areas of Regression
- none

## Testing
- none

## Code Review
@maxwellpeterson-wf
@evanweible-wf
@dustinlessard-wf 
@jayudey-wf

### CODE REVIEW

**Comment by dustinlessard-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1 @jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA +1, doc change only

Merging into master

**Pull request merged**
