### PR TITLE
CP-1081 Update README with warning about supported platforms on CI servers.

### PR DESCRIPTION
**Pull request by dustinlessard-wf**
For consideration:
@trentgrover-wf @evanweible-wf @maxwellpeterson-wf @jayudey-wf

### CODE REVIEW

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf docs only change

**Comment by jayudey-wf** [comment]
QA +1, doc change only

Merging into master

**Pull request merged**
