### PR TITLE
Create dependabot.yml

### PR DESCRIPTION
**Pull request by robbecker-wf**
Set up an initial dependabot yaml

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by evanweible-wf — APPROVED** [review]

**Comment by autobot-wk** [comment]
Skynet test results failed initially for this build but were approved by evan.weible
https://wf-skynet-hrd.appspot.com/apps/test/smithy/3982650/1
Approval message: Failures on stable and above are known and unrelated to change under test

**Comment by evanweible-wf** [comment]
QA +1 CI passes
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
