### PR TITLE
CP-2824 Fixes for compatibility with Dart 1.20.x

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
Dart 1.20.0 and 1.20.1 were released and change the default behavior to no longer generate `packages/` directories. This breaks some of our existing tooling.

## Solution
- Use `--packages` option instead of `--package-root` option
- Always set `config.coverage.pubServe = true` for browser tests
- Upgrade minimum `dartdoc` dependency
- **Bonus:** removed some test fixtures that weren't being used (maybe a bad merge)

## Testing
- [ ] CI passes
- [ ] Install into a few consumer projects and verify that all tasks work as expected
  - [ ] fluri
  - [ ] w_transport
  - [ ] truss

## Code Review
@trentgrover-wf 
@maxwellpeterson-wf 
@dustinlessard-wf 
@jayudey-wf 
@sebastianmalysa-wf

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentonsmith-wf** [comment]
Can you bump the version of resource to ^2.0.0(https://github.com/dart-lang/resource/releases/tag/2.0.1 is the actual desired version) in this?

**Comment by evanweible-wf** [comment]
@trentonsmith-wf good catch, I've widened the dependency range

**Comment by dustinlessard-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - passing CI
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - installed into fluri and w_transport and verified that tasks were working as expected
 - installed into truss and verified that all ddev tasks were as expected on 1.20.1 and 1.19.1
- [ ] Unit test created/updated
- [ ] All unit tests pass 

Merging into master.

**Pull request merged**
