### PR TITLE
Analyze: support strong mode

### LINKED ISSUE #111: Support strong mode for the analyze task
`dartanalyzer --strong ...`

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
- Fixes #111 

## Changes
**Source:**
- Add `strong` option for analyze config
- Add `--strong` flag to analyze CLI
- Add `strong` param to analyze API

**Tests:**
- Integration test for project with static typing issues and `--no-strong`
- Integration test for project with static typing issues and `strong`

## Areas of Regression
- n/a

## Testing
- CI passes

## Code Review
@trentgrover-wf
@maxwellpeterson-wf 
@dustinlessard-wf
@jayudey-wf

### CODE REVIEW

**Comment by evanweible-wf** [comment]
I also snuck an update to the changelog in here.

**Comment by dustinlessard-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@trentgrover-wf @maxwellpeterson-wf @dustinlessard-wf rebased against latest master

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - passing CI
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Comment by jayudey-wf** [comment]
@rosie run_merge_script

**Pull request merged**
