### PR TITLE
AF-1586 Add assertCheckedModeEnabled() utility.

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Description
Adds an `assertCheckedModeEnabled()` utility that will throw if the current Dart process is not running in checked mode. The intended use case is for tests to ensure that a package's test suite is running in checked mode for added assurances.

## Changes

Added a `checked_mode.dart` entry point with an `assertCheckedModeEnabled()` utility.

## Testing
- [ ] CI passes
- [ ] `dart test/unit/vm/checked_mode_test.dart` fails

## Code Review
@Workiva/app-frameworks @robbecker-wf

### CODE REVIEW

**Comment by corwinsheahan-wf** [comment]
+10 
* CI Passes

**Comment by jayudey-wf** [comment]
pending question about a test verifying the non checked cased

**Comment by jayudey-wf** [comment]
QA +1

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
  - passing CI
- [ ] Security review (if required)
- [ ] Unit tests created/updated
- [ ] All unit tests pass
- [ ] Rosie has run and reports properly the release the ticket will be included in

Merging into master.

**Comment by jayudey-wf** [comment]
@Workiva/release-management-pp

**Pull request merged**
