### PR TITLE
CP-3178 Release dart_dev 1.5.4

### PR DESCRIPTION
**Pull request by rm-astro-wf**
Pulls Included in Release:
* [CP-2124: Add Debug Flag to Test Task](https://github.com/Workiva/dart_dev/pull/195)

Requested by: @evanweible-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.5.3...version-bump-dart_dev-1-5-4
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.5.3...1.5.4

### CODE REVIEW

**Comment by evanweible-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for you

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
