### PR TITLE
CP-1531 Release dart_dev 1.2.0

### PR DESCRIPTION
**Pull request by charliekump-wf**
JIRA: https://jira.webfilings.com/browse/CP-1531

Releases that need to go out at the same time (if any): 

JIRA and PR's included in this release: 

 CP-1604  - Functional Coverage Working For Real I Promise  - https://github.com/Workiva/dart_dev/pull/145

 CP-1329  - Create dart test runner generator, dart_dev  - https://github.com/Workiva/dart_dev/pull/124

 CP-1768  - Allow a provided pub serve port  - https://github.com/Workiva/dart_dev/pull/153

 CP-1754  - Add fish completions  - https://github.com/Workiva/dart_dev/pull/149

 CP-1794  - Add completions.dart support  - https://github.com/Workiva/dart_dev/pull/151

 CP-1811  - Add Local Task Integrations  - https://github.com/Workiva/dart_dev/pull/150

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.1.2...CP-1531_release_1.2.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.1.2...1.2.0

### CODE REVIEW

**Comment by dustinlessard-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by bencampbell-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
Manual CI

- [ ] `ddev analyze`
- [ ] `ddev format`
- [ ] `ddev test --integration`
- [ ] `ddev coverage --integration`

QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
