### PR TITLE
CP-844 Release dart_dev 1.0.0

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-844

JIRA and PR's included in this release: 

 CP-827  - Add line-length option to format task.  - https://github.com/Workiva/dart_dev/pull/18
 CP-822  - CLI improvements & cleanup.  - https://github.com/Workiva/dart_dev/pull/13
 CP-823  - Integration Tests, darv_dev  - https://github.com/Workiva/dart_dev/pull/15
 CP-841  - Add a CHANGELOG, dart_dev  - https://github.com/Workiva/dart_dev/pull/28
 CP-843  - New Task: Copy License  - https://github.com/Workiva/dart_dev/pull/16
 CP-808  - dart_dev initial implementation  - https://github.com/Workiva/dart_dev/pull/3
 CP-849  - Add Apache 2.0 license, dart_dev  - https://github.com/Workiva/dart_dev/pull/19
 CP-839  - New Task: Code Coverage  - https://github.com/Workiva/dart_dev/pull/25
 CP-842  - Ready pubspec.yaml for OSS, dart_dev  - https://github.com/Workiva/dart_dev/pull/32
 CP-851  - Dartfmt license header whitespace  - https://github.com/Workiva/dart_dev/pull/35
 CP-852  - Make copy license task compatible with dart formatter  - https://github.com/Workiva/dart_dev/pull/37
 CP-847  - Add all required dependencies to install instructions  - https://github.com/Workiva/dart_dev/pull/33
 CP-858  - Travis CI, dart_dev  - https://github.com/Workiva/dart_dev/pull/39
 CP-859  - Codecov.io, dart_dev  - https://github.com/Workiva/dart_dev/pull/40
 CP-864  - Explicitly exit process when dart_dev has finished  - https://github.com/Workiva/dart_dev/pull/46

Diff Between Last Tag and Proposed Release: N/A

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
