### PR TITLE
CP-1397 Release dart_dev 1.1.1

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-1397

Releases that need to go out at the same time (if any): 

JIRA and PR's included in this release: 

 CP-1398  - Update logic around including unit tests by default  - https://github.com/Workiva/dart_dev/pull/134

 CP-1399  - Update changelog for 1.1.0 and 1.1.1  - https://github.com/Workiva/dart_dev/pull/135

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.1.0...CP-1397_release_1.1.1

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

since travis CI is failing due to non-related issues (coverage package not working on dart-sdk 1.14.1+), i pulled down this branch and ran through all of the commands from the travis yaml and verified they were working as expected on 1.14.0)

**Pull request merged**
