### PR TITLE
CP-1108 Release dart_dev 1.0.4

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-1108

JIRA and PR's included in this release: 

 CP-1124  - Fix browser file detection (dart2js output changed)  - https://github.com/Workiva/dart_dev/pull/98
 CP-1125  - Fix incorrect grammer in format task output  - https://github.com/Workiva/dart_dev/pull/97
 CP-1122  - Bash completions  - https://github.com/Workiva/dart_dev/pull/96

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.0.3...CP-1108_release_1.0.4

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
