### PR TITLE
CP-1941 Release dart_dev 1.4.0

### PR DESCRIPTION
**Pull request by charliekump-wf**
JIRA: https://jira.webfilings.com/browse/CP-1941

Releases that need to go out at the same time (if any): 

JIRA and PR's included in this release: 

======= dart_dev 1.4.0 items =======

 REF-956  - Add --check option to dart_dev gen-test-runner  - https://github.com/Workiva/dart_dev/pull/163

======= end =======

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.3.0...CP-1941_release_1.4.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.3.0...1.4.0

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
