### PR TITLE
CP-2404 Fix bug when gen-test-runner --check runs on Smithy

### PR DESCRIPTION
**Pull request by georgelesica-wf**
It seems that while `gen-test-runner --check` works locally, it fails on Smithy, at least some of the time. I suspect that the directory listing order just isn't stable across platforms. Sorting the test files fixes the problem. I also added some more helpful error output. @evanweible-wf @maxwellpeterson-wf

### CODE REVIEW

**Comment by rmconsole-wf** [comment]
@georgelesica-wf
* It looks like you have not included any tickets in the title of this PR, but this repo requires tickets for all pull requests. Please create a ticket for this change, or click <a href='https://w-rmconsole.appspot.com/api/v1/pulls/80102067/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by georgelesica-wf** [comment]
@jayudey-wf I figured out the formatter issue, fixed with a `git clean`, but now the tests are randomly failing. This test suite won't run for me locally, would you mind running it and debugging if necessary?

**Comment by georgelesica-wf** [comment]
@jayudey-wf the build you started manually passed, but it didn't get associated with the PR...

**Comment by theisensanders-wf** [comment]
@georgelesica-wf @jayudey-wf Any update on this?

**Comment by georgelesica-wf** [comment]
@theisensanders-wf I'm happy with it, just needs some review from CP.

**Comment by evanweible-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@maxwellpeterson-wf @trentgrover-wf @dustinlessard-wf @sebastianmalysa-wf @srinivasdhanwada-wf

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by georgelesica-wf** [comment]
@jayudey-wf I think we're ready for merge here.

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - installed into separate project and verified that `pub run dart_dev gen-test-runner --check` was able to complete as expected
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Pull request merged**
