### PR TITLE
dependabot: ignore majors

### PR DESCRIPTION
**Pull request by robbecker-wf**
Ignore major version bumps for all packages

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by autobot-wf** [comment]
Skynet test results failed initially for this build but were approved by rob.becker
https://wf-skynet-hrd.appspot.com/apps/test/smithy/3985442/1
Approval message: known failures in newer Dart

**Comment by robbecker-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Comment by autobot-wk** [comment]
Skynet test results failed initially for this build but were approved by evan.weible
https://wf-skynet-hrd.appspot.com/apps/test/smithy/3985442/1
Approval message: Known unrelated failures on stable and above

**Pull request merged**
