### PR TITLE
CP-1128 Update CHANGELOG with 1.0.3, 1.0.4 releases

### PR DESCRIPTION
**Pull request by evanweible-wf**
**DOCS ONLY**

## Issue
- `CHANGELOG.md` is missing the last two releases

## Changes
- Update changelog

## Areas of Regression
- n/a

## Testing
- n/a

## Code Review
@trentgrover-wf
@maxwellpeterson-wf 
@dustinlessard-wf
@jayudey-wf

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf ready for merge (docs only change)

**Comment by jayudey-wf** [comment]
QA +1, doc change only

Merging into master

**Comment by jayudey-wf** [comment]
@rosie run_merge_script

**Pull request merged**
