### PR TITLE
Export the ArgResults utils

### PR DESCRIPTION
**Pull request by todbachman-wf**
### Problem:
dart_dev has some fine ArgResults utilities that are useful for authors of new dart_dev tools.

### Solution:
Added an export for `src/utils/arg_results_utils.dart`.

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by evanweible-wf — COMMENTED** [review]
Mind adding a changelog entry?

**Comment by todbachman-wf** [comment]
I always forget to add a changelog entry. 🤕  Done.

**Review by evanweible-wf — APPROVED** [review]

**Comment by evanweible-wf** [comment]
QA +1

- [x] CI passes

**Comment by todbachman-wf** [comment]
@Workiva/release-management-pp

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
