### PR TITLE
CP-917 Add pub badge to readme.

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
#31 

## Changes
Added pub badge to readme.

## Areas of Regression
n/a

## Testing
n/a

## Code Review
@trentgrover-wf
@maxwellpeterson-wf 
@dustinlessard-wf
@jayudey-wf

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA +1, verified that badge was appearing as appropriately

Merging into master

**Comment by jayudey-wf** [comment]
@rosie run_merge_script

**Pull request merged**
