### PR TITLE
CP-851 Dartfmt license header whitespace

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
Missed a dartfmt run.

## Changes
Ran dartfmt, all of the newly added license headers had whitespace changes.

## Areas of Regression
- n/a

## Testing
- n/a

## Code Review
@trentgrover-wf
@maxwellpeterson-wf 
@dustinlessard-wf
@jayudey-wf

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for merge, changes only to comments.

**Comment by jayudey-wf** [comment]
go @rmconsole-wf

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - white space only change
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Pull request merged**
