### PR TITLE
Minor pubspec and readme cleanup

### PR DESCRIPTION
**Pull request by parlough**

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by tomconnell-wf — APPROVED** [review]
Apologies on the slow turnaround on this PR.

**Comment by tomconnell-wf** [comment]
# QA +1

Documentation only, no QA steps needed.

@Workiva/release-management-pp - Rosie, :shipit:

**Comment by alexandercampbell-wk** [comment]
Thanks for the contribution @parlough! Sorry about the delay getting that merged.

**Pull request merged**
