### PR TITLE
Fixes for Windows compatibility

### PR DESCRIPTION
**Pull request by evanweible-wf**
There are several paths that we're using in our executable and in the run script that we generate and we need to construct them with the appropriate APIs from `package:path` to ensure they work when running on Windows. This PR does that.

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by autobot-wk** [comment]
Skynet test results failed initially for this build but were approved by evan.weible
https://wf-skynet-hrd.appspot.com/apps/test/smithy/3860935/1
Approval message: Known failures on alpha and beta.

**Review by todbachman-wf — APPROVED** [review]

**Comment by autobot-wf** [comment]
Skynet test results failed initially for this build but were approved by evan.weible
https://wf-skynet-hrd.appspot.com/apps/test/smithy/3863889/1
Approval message: Known failures on beta and alpha.

**Comment by evanweible-wf** [comment]
QA +1
- [x] Had a Windows user manually verify that this fixes the issue with the generated run script.
- [x] CI passes on stable, which now includes running the entire test suite on Windows.

@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
