### PR TITLE
CP-2661 Release dart_dev 1.5.0

### PR DESCRIPTION
**Pull request by rmconsole2-wf**
Pulls Included in Release:
* [CP-2272 Implemented task that allows a user to run browser based dart unit tests on saucelabs](https://github.com/Workiva/dart_dev/pull/148)

Requested by: charliekump-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.4.2...version-bump-dart_dev-1-5-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.4.2...1.5.0

### CODE REVIEW

**Comment by rmconsole-wf** [comment]
@rmconsole2-wf, @edjackson+rmconsole-wf
* It looks like you have not included any tickets in the title of this PR, but this repo requires tickets for all pull requests. Please create a ticket for this change, or click <a href='https://w-rmconsole.appspot.com/api/v1/pulls/86359088/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
