### PR TITLE
CP-2954 Release dart_dev 1.5.3

### PR DESCRIPTION
**Pull request by rmconsole2-wf**
Pulls Included in Release:
* [CP-2990 Fix README dependencies so that users can pull down the latest dart_dev](https://github.com/Workiva/dart_dev/pull/194)
* [RAP-1367 Add hyphen to local task regex](https://github.com/Workiva/dart_dev/pull/196)

Requested by: @evanweible-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.5.2...version-bump-dart_dev-1-5-3
Diff Between Last Tag and New Tag: https://github.com/Workiva/dart_dev/compare/1.5.2...1.5.3

### CODE REVIEW

**Comment by evanweible-wf** [comment]
+1

**Comment by charliekump-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
