### PR TITLE
CP-1209 Release dart_dev 1.1.0

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-1209

JIRA and PR's included in this release: 

 CP-1212  - Update README.md for broken link  - https://github.com/Workiva/dart_dev/pull/118
 CP-1225  - add docs badge, dart_dev  - https://github.com/Workiva/dart_dev/pull/119
CP-1303 Fail coverage task if a unit tests fails  - https://github.com/Workiva/dart_dev/pull/125

 CP-1318  - Add ability to pass in test name as a parameter to test task  - https://github.com/Workiva/dart_dev/pull/126

 CP-1334  - copy-license: catch FSE when reading non-utf8 file  - https://github.com/Workiva/dart_dev/pull/129

 CP-1393  - Update test task to observe `--no-unit` flag  - https://github.com/Workiva/dart_dev/pull/131

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/dart_dev/compare/1.0.6...CP-1209_release_1.1.0

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

due to CI failing due to non-related issues ran through all CI commands locally on dart sdk 1.14.0 version

```
pub run dart_dev format --check
...
Your Dart code is good to go!

pub run dart_dev analyze
...
Analysis completed.

pub run dart_dev test --integration
...
03:36 +44: All tests passed!

pub run dart_dev coverage --integration 
...
Coverage collected.
```

**Pull request merged**
